# Generated by Django 4.2.5 on 2023-10-09 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='user_followered',
            new_name='user_followed',
        ),
    ]
