# Generated by Django 4.2.5 on 2023-10-15 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
